version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: chmod +x ./gradlew testDevDebugUnitTest
      - run:
          name: Run Packaging
          command: chmod +x ./gradlew assembleDevDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results